### PR TITLE
Add z-index fix to the README

### PR DESCRIPTION
**Pull request by jankapunkt**
I just faced this issue when using this with Bootstrap4 and I just found, that [some other person already raised this issue before](https://github.com/TheLastProject/CSSBox/issues/3). So I think it is a good thing to mention this in the README in order to make others (especially beginners) understand this immediately.

### CODE REVIEW

**Comment by TheLastProject** [comment]
Why not just increase the default z-index instead? https://github.com/TheLastProject/CSSBox/issues/3#issuecomment-685806044

**Comment by jankapunkt** [comment]
Haha I read the linked comment again and now understand how it was mentioned :-)  There are many frameworks that use different `z-index` so maybe it should be `999999` or something?

**Comment by TheLastProject** [comment]
Sounds good to me

**Comment by jankapunkt** [comment]
Unfortunately I can't switch the target branch (only the base branch) so I just added the commits. I am also too scared to rebase as it messed things up in the past.

**Comment by TheLastProject** [comment]
Thanks :)

**Pull request merged**
